sources:
  - name: src
    database: sourcedb
    schema: mk_mall
    tables:
      - name: customers
      - name: nations
        columns:
          - name: n_nationkey
            data_tests:
              - unique
              - not_null
      - name: regions
      - name: v_nations
      - name: lineitems
      - name: parts
      - name: suppliers

      - name: partsupps
      - name: orders
        config:
          freshness: 
            warn_after: {count: 3, period: day}
            error_after: {count: 3, period: day}
          loaded_at_field: o_orderdate::timestamp_ntz
  
  - name: src1
    database: mkmotors_dev
    schema: staging
    tables:
      - name: stg_employees
        
  
  - name: src3
    database: analytics
    schema: dbt_arjita
    tables:
      - name: stg_employees
       

          
  - name: src4
    database: analytics
    schema: dbt_akushwaha
    tables:
      - name: suppliers
        
        