sources:
  - name: src
    database: sourcedb
    schema: mk_mall
    tables:
      - name: customers
      - name: nations
        columns:
        - name: nation_id
          data_type: int
          constraints:
          - type: not_null
          - type: unique   

        - name: name
          data_type: string
          constraints:
            - type: not_null

        - name: updated_at
          data_type: timestamp
        
        - name: region_id
          data_type: int
          tests:
            - relationships:
                arguments:
                  to: ref('stg_region')
                  field: region_id
      - name: regions
      - name: v_nations
      - name: lineitems
      - name: parts
      - name: suppliers

      - name: partsupps
      - name: orders
        config:
          freshness: 
            warn_after: {count: 3, period: day}
            error_after: {count: 3, period: day}
          loaded_at_field: o_orderdate::timestamp_ntz
  
  - name: src1
    database: mkmotors_dev
    schema: staging
    tables:
      - name: stg_employees
        
  
  - name: src3
    database: analytics
    schema: dbt_arjita
    tables:
      - name: stg_employees
       

          
  - name: src4
    database: analytics
    schema: dbt_akushwaha
    tables:
      - name: suppliers
        
        